name: multipockga

channels:
  - conda-forge

dependencies:
  - python=3.10
  - numpy
  - pandas
  - pyyaml
  - scipy
  - tqdm
  - requests
  - rdkit
  - biopython
  - pip
  - pip:
      - omegaconf
      - selfies
      - func-timeout
      - gdown
      - -e .